### PR TITLE
Add Bohm/gyro-Bohm transport model

### PR DESCRIPTION
**Pull request by theo-brown**
This is a WIP draft of adding the BgB transport model. 

BgB would be a useful feature to have as there are large databases of historic simulation runs that have been run with the BgB model, in order to keep run times as low as possible while still capturing empirical physics. This is particularly the case for JET and STEP at UKAEA. Having BgB in TORAX would enable rapid validation and cross-checking of solutions for us at UKAEA.

### Todo list
- [x] Check using correct TORAX terms
- [x] Check using correct BgB model equations
- [x] Check D_e and v_e
- [x] ~~Write unit tests~~ Other transport models do not have unit tests
- [x] Write integration test
- [x] Write documentation

### CODE REVIEW

**Comment by jcitrin** [comment]
Excellent, thanks for developing this. Indeed it was on the long TODO list, so this is much appreciated.

**Comment by theo-brown** [comment]
Ok, all the guts should be here now. I need to do some tinkering with the integration test, because it's currently not converging correctly; I think this is probably due to a choice of BgB coefficients rather than anything more nefarious.

**Comment by jcitrin** [comment]
Awesome, thanks. Recommend merging main into your branch since there is a conflict currently. Let me know if I can help with anything with the test.

**Comment by jcitrin** [comment]
@theo-brown , thanks again for this! Merged with https://github.com/google-deepmind/torax/commit/a12dc1816fda98dc9b3f3a581d77f124dc6f9bff . 

A few minor changes from the original PR:
1. Moved the model description to the physics_models.rst section of the docs, and also updated configuration.rst . For the future, I will add documentation to the documentation on how to extend and test the documentation :)
2. Added sanity checks for the bohmgyrobohm chi and D inputs (enforce positivity)
3. Various minor cleanups for linter satisfaction
4. Changed the model description variables in the docs to be more TORAX-specific
5. Added the license header to the new file

**Comment by theo-brown** [comment]
Amazing! Thank you so much for merging it and for your invaluable help along the way. Cleanups sound top notch, thank you! Will get the Google linter set up before my next PR.

**Pull request merged**
