### PR TITLE
Fix Bohm-gyro-Bohm model particle transport

### PR DESCRIPTION
**Pull request by theo-brown**
Implement fixes described in #403.

**Tasks:**
- [x] Add missing `rho_b` term to `v_face_el`
- [x] Solve `nan` on-axis for `D_face_el`
- [x] Add particle transport test case

### CODE REVIEW

**Comment by jcitrin** [comment]
For the test case: to avoid test bloat perhaps it's better to just extend the existing BgB test to include particle transport as well

**Comment by theo-brown** [comment]
Note that my plasma experience is not strong enough yet to sense-check the results of the test case.

**Comment by jcitrin** [comment]
Thanks for all this.

About sense-checking the results. Here's what it looks like:

image


The bulk ne profile looks OK, but things are a bit wonky in the "pedestal" region. This is because of inappropriate defaults for this case. The ne boundary condition default is nebound=0.85*nGW (0.85 Greenwald fraction), but neped is set as 0.7e20, which ends up under that value for this case. We later plan to introduce machine-specific defaults for config, but are not there yet.

When introducing more appropriate density settings, i.e.
```
    'runtime_params': {
        'profile_conditions': {
            'nbar': 0.8,
            'neped': 0.8,
            'neped_is_fGW': True,
            'ne_bound_right': 0.5,
            'ne_bound_right_is_fGW': True,
        },
```

we get 
image

which looks better.

Only other comment for the review is that the name BgB test case in tests/sim.py also needs to be updated.

I've done above modifications on our end, and this will included in the merge, so no further action is necessary :)

**Comment by jcitrin** [comment]
Merged with ab28a713

**Pull request merged**
